---
bg: 'Gon.png'
layout: post
title:  "golang函数的使用"
crawlertitle: "golang"
summary: ""
date:   2020-03-03 18:30:00 +0800
categories: posts
tags: 'golang'
author: 宋天
---

Golang中的函数的使用和特点



- 函数的类型叫作函数签名，如果两个函数的参数类型序列和返回类型序列相同，那么两个函数类型相同, 和参数的名称和是否factored（把相同类型参数整合在一起写，例如`func get(i, j int)`）无关
- 函数是值传递，所以函数接收每个变量的一份拷贝，修改拷贝不会影响调用者，但是，如果参数包含一些引用，例如指针，切片，哈希表，函数，channel，函数对这些修改会响应内部指针的内容从而影响调用者
- 有时会碰到一些没有Body的函数，这个函数是被其他不是Go的语言实现的，所以定义了方法签名
- golang.org/x/... 这个包包含一些网络，国际文本处理，加密，开发工具等，不在标准库里面，因为一些在还处于开发阶段或者不是很常用


## 递归

- 函数是可以递归的，既可以自己调用自己，对于某些数据结构，递归函数是解决遍历这些数据结构的很好的方法
- 许多编程语言有一个固定长度的函数调用栈，通常是64KB-2MB, 在有很深层级的函数调用时，要注意StackOverFlow（栈溢出）错误,Go使用可变长度的函数调用栈，刚开始很小，可以随着需要增长到GB级别

## 返回多个值

- 即使在错误的情况下，resp.Body也必须关闭，goGC会回收不用的内存，但不会回收不用的操作系统资源，例如打开的文件和网络连接，必须显示关闭。
- 多值函数可以被应用于函数return语句和函数参数
- bare return， 在函数签名return已经声明了变量名，这些真正的return处只需要单独写一个return

```go
func A() (i int) {
    i = 10
    return
}
```

## 错误

- 函数可以返回一个错误来表示这个函数没有正常处理，调用者可以根据这个错误来执行特定的操作，错误通常是返回值的最后一个，可以是一个bool或者error类型，取决于错误是一个还是多个
- 调用者处理错误的五种方式
    1. 传播错误，可以直接return err，也可以使用fmt.Errorf()对已有错误前缀增加额外的信息，比如在哪调用的，当到main函数的时候，错误会有一个错误原因链，所以不要在fmt.Errorf里面写首字母大写或者换行
    2. 重试，当错误是短暂的或者不可预测的问题，可以通过尝试特定的次数。
    3. 打印并终止程序，通常由main函数来执行，使用os.Exit或者log.Fatal来终止
    4. 打印并继续
    5. 忽视错误
- io.EOF， 一种特殊的错误来标志文件读取结束


## 函数Values

- 函数是第一类Values, 函数值有类型，可以被赋值，也可当做参数传递
- 可以声明一个函数，零值为nil, nil函数不能调用，会panic
- 是不可比较的，不能用于map的key,只能和nil比较
- 函数值使函数不仅在参数数据上，而且在功能上都有所改变，比如strings.Map(func, string), 会对string的每个character进入func的处理


## 匿名函数

- 匿名函数相比普通的函数，就是在func关键字之后没有名字
- 这样的函数可以引用外部的变量，就是其他语言中的闭包，所以函数值不仅仅是代码，而且还有状态

```go
func squares() func() int {
    var x int 
    return  func() int {
        x++
        return x * x
    }
}

func main() {
    f:=squares()
    fmt.Println(f()) //1
    fmt.Println(f()) //4
    fmt.Println(f()) //9
}

```
- 匿名函数递归时必须先声明，即不能使用短表里表达式赋值

### 循环变量的陷阱

```go
var rmdirs []func()
for _, dir := range tempDirs() {
    os.MkdirAll(dir, 0755)
    rmdirs = append(rmdirs, func(){
        os.RemoveAll(dir)
    })
}

```

- 在上面的代码中，有一个问题，在rmdirs里面的函数引用了for遍历中的变量，所以这个dir最终都是一个值，也就是最后只会删除一个目录
- 产生这样的原因是for只使用一个地址来存变量，在遍历的过程中，不断的覆盖这个值(这么做也是一种优化，每次声明新的变量在大多数情况下是不必要的)，所以dir的值遍历完就是最后一个值
- 修复上面问题的方法是在for循环内重新声明另一个变量，然后赋值给它，虽然看起来很奇怪，但确实有效的
- 相同的情况在go语句或者defer中也可能出现，因为这些函数都是等循环执行完才执行

## 可变函数

- 参数的数量是任意多个的，在声明函数参数时使用省略号`...`来表示某个参数是任意多个的，只能是最后一个参数
- 调用者传递任意个数的参数都可以调用此函数，也可以显示使用`...`对切片来使用以达到传递切片时拆分成任意参数的目的
  
```go
func sum(vals ...int) int {
    sum := 0
    for _, v := range vals {
        sum += v
    }
    return sum
}

sum()
sum(0)
sum(1,2,3)
sum([]int{1,2,3}...)

```
- 尽管可变函数和参数时切片的函数类似，但这两种函数是不一样的

## defer函数调用

- defer函数调用就是在普通函数调用前多写一个defer， 它的执行时机不是在对应的代码处，而是函数结束时执行，无论函数是成功或者失败返回，异常，Panic等，被推迟执行的函数按照先进后出的方式来执行
- 经常用于open和close, connect和disconnect, lock和unlock等确保资源的释放
- 使用defer可用在进入和退出函数时对复杂做一些debug，例如下面, （不要忘记defer函数后面的执行括号）

```go
func bigSlowOperation(){
	defer trace("bigSlowOperation")()
	time.Sleep(10 * time.Second)
}

func trace(msg string) func() {
	start := time.Now()
	log.Printf("enter %s", msg)
	return func() {log.Printf("exit %s (%s)", msg, time.Since(start))}
}
// output
// 2019/12/22 13:11:55 enter bigSlowOperation
// 2019/12/22 13:12:05 exit bigSlowOperation (10.003695404s)
```
- defer可以获得更新后的返回结果的值，结合返回变量名称可以很容易在多个返回语句的情况下打印出返回结果，defer甚至可以修改返回结果的值
- 在for循环中使用defer要格外小心，因为defer要函数最后才会执行，例如在for中使用defer关闭文件，很有可能用尽file descriptor

## Panic

一些运行时错误，例如数组越界和空指针引用, 当Go检查到这些错误，会发生panic

- panic发生时，那个goroutine将所有的defered函数执行完，程序崩溃退出并打印错误栈
- 可以使用panic函数显式调用，处理不可能发生的逻辑
- panic相比其他语言的异常有所不同，panic使用程序崩溃，通常是非常严重的错误，可以认为产生panic即是程序有bug, 正常的异常可以被error返回值优雅的处理
- runtime.Stack可以将错误栈写入buffer里面

## Recover

在defered函数中调用recover函数，当包含defered函数的那个函数panic时，recover将会从panic状态中断，并返回panic值，panicking的函数不会从失败的地方继续，而是正常返回，如果在其他情况下调用panic, 它会返回nil并没其他的什么效果

- recover任意panic可能会造成一些问题，比如资源没有合理释放等，这种情况很难察觉，所以应该根据panic值有选择性去进行recover